const TRADE_ICONS = {
    'AC / Refrigeration technician': 'ti ti-snowflake',
    'Aluminium / Glass installer': 'ti ti-window',
    'Auto electrician': 'ti ti-bolt',
    'Auto mechanic': 'ti ti-tool',
    'Auto painter / Sprayer': 'ti ti-spray',
    'Battery charger / Inverter tech': 'ti ti-battery-automotive',
    'Borehole / Water technician': 'ti ti-droplet',
    'Bricklayer / Mason': 'ti ti-building',
    'Cabinet / Furniture maker': 'ti ti-sofa',
    Carpenter: 'ti ti-hammer',
    'Caterer / Event cook': 'ti ti-tools-kitchen-2',
    'CCTV / Security installer': 'ti ti-device-cctv',
    'Cleaner / Janitorial': 'ti ti-sparkles',
    'Cobbler / Shoe maker': 'ti ti-shoe',
    'Disk jockey (DJ)': 'ti ti-music',
    'Driver (private / commercial)': 'ti ti-car',
    'Dry cleaner / Laundry': 'ti ti-wash-machine',
    Electrician: 'ti ti-bolt',
    'Event decorator / Canopy': 'ti ti-balloon',
    'Fashion designer / Tailor': 'ti ti-scissors',
    'Gas cooker technician': 'ti ti-flame',
    'Generator technician': 'ti ti-battery-automotive',
    'Graphic designer / Printer': 'ti ti-printer',
    'Hairdresser / Barber': 'ti ti-cut',
    'Iron bender / Steel fixer': 'ti ti-building-bridge',
    'Interior decorator': 'ti ti-armchair',
    'Interlocking / Paving stone': 'ti ti-grid-dots',
    'Makeup artist': 'ti ti-palette',
    'Motorcycle / Okada mechanic': 'ti ti-motorbike',
    'Nail technician': 'ti ti-hand-finger',
    'Painter / Decorator': 'ti ti-paint',
    'Panel beater': 'ti ti-car-crane',
    'Phone / Laptop repair': 'ti ti-device-mobile',
    'Photographer / Videographer': 'ti ti-camera',
    'Plasterer / POP ceiling': 'ti ti-home',
    Plumber: 'ti ti-droplet',
    'POS / Signage installer': 'ti ti-sign-left',
    Roofer: 'ti ti-home-2',
    'Satellite / TV installer': 'ti ti-satellite',
    'Solar installer': 'ti ti-sun',
    Tiler: 'ti ti-grid-dots',
    'Tricycle (Keke) mechanic': 'ti ti-bike',
    Upholsterer: 'ti ti-armchair',
    'Vulcanizer / Tyre repair': 'ti ti-circle-dot',
    'Welder / Fabricator': 'ti ti-flame',
    Other: 'ti ti-dots',
};

export function tradeIcon(trade) {
    return TRADE_ICONS[trade] || 'ti ti-briefcase';
}
