<?php

/**
 * Hierarchical job categories for work-log classification.
 *
 * Structure: category => [ subcategory label => review_phrase ]
 *
 * review_phrase is private metadata — used only in WhatsApp review invites
 * (e.g. "thanks for trusting me with your {review_phrase}").
 * It is never shown on the public profile or job timeline.
 */
return [
    'Software, Web & E-commerce Development' => [
        'Web Developer' => 'web development work',
        'Frontend Developer' => 'frontend development work',
        'Backend Developer' => 'backend development work',
        'Full-Stack Developer' => 'full-stack development work',
        'PHP Developer' => 'PHP development work',
        'Laravel Developer' => 'Laravel development work',
        'Python Developer' => 'Python development work',
        'Django Developer' => 'Django development work',
        'Ruby on Rails Developer' => 'Ruby on Rails development work',
        'Node.js Developer' => 'Node.js development work',
        'Java Developer' => 'Java development work',
        'C# Developer' => 'C# development work',
        'Go Developer' => 'Go development work',
        'Rust Developer' => 'Rust development work',
        'WordPress Developer' => 'WordPress development work',
        'Shopify Developer' => 'Shopify development work',
        'E-commerce Developer' => 'e-commerce development work',
        'API Developer' => 'API development work',
        'Integration Specialist' => 'integration work',
        'SaaS Developer' => 'SaaS development work',
        'SQL Developer' => 'SQL development work',
        'Database Administrator' => 'database administration work',
        'BigQuery / SQL Work' => 'BigQuery and SQL work',
        'Other software / web work' => 'software development work',
    ],

    'Mobile, Game & AR/VR Development' => [
        'Mobile App Developer' => 'mobile app development work',
        'Android Developer' => 'Android development work',
        'iOS Developer' => 'iOS development work',
        'React Native Developer' => 'React Native development work',
        'Flutter Developer' => 'Flutter development work',
        'Cross-platform Developer' => 'cross-platform development work',
        'Mobile Game Developer' => 'mobile game development work',
        'Game Developer' => 'game development work',
        '2D Games' => '2D game development work',
        '3D Games' => '3D game development work',
        'Game UI/UX' => 'game UI/UX work',
        'Game Assets' => 'game asset work',
        'AR/VR Developer' => 'AR/VR development work',
        'Other mobile / game work' => 'other mobile / game work',
    ],

    'Data, AI & Analytics' => [
        'Data Analyst' => 'Data analysis',
        'Data Scientist' => 'data Scientist work',
        'Data Engineer' => 'Data engineering work',
        'Data Services' => 'data services',
        'Data Entry' => 'data entry work',
        'Data Cleaning' => 'data cleaning work',
        'Data Labeller' => 'Data labelling',
        'Machine Learning Engineer' => 'Machine Learning engineering work',
        'AI Engineer' => 'AI engineering work',
        'Model Training' => 'model training work',
        'AI Automation' => 'AI automation work',
        'Prompt Engineer' => 'Prompt engineering work',
        'Big Data Engineer' => 'Big Data engineering work',
        'Dashboard Creation' => 'dashboard creation',
        'BI Developer' => 'BI development work',
        'Tableau Developer' => 'Tableau development work',
        'Power BI Developer' => 'Power BI development work',
        'Research & Reports' => 'research and reporting',
        'Market Research' => 'market research',
        'Survey Design' => 'survey design',
        'Other data / AI work' => 'other data / AI work',
    ],

    'DevOps, Cloud, IT, Cybersecurity & Hardware' => [
        'DevOps Engineer' => 'DevOps engineering work',
        'Cloud Engineer' => 'Cloud engineering work',
        'Cloud Architect' => 'Cloud architecture work',
        'CI/CD Engineer' => 'CI/CD engineering work',
        'Server Setup' => 'server setup',
        'Cloud Migration' => 'cloud migration',
        'Infrastructure Monitoring' => 'infrastructure monitoring',
        'Site Reliability Engineer' => 'Site Reliability engineering work',
        'Systems Administrator' => 'Systems administration',
        'Linux Administrator' => 'Linux administration',
        'Network Engineer' => 'Network engineering work',
        'IT Support Technician' => 'IT Support technician work',
        'Helpdesk Support' => 'helpdesk support',
        'Cybersecurity Analyst' => 'Cybersecurity analysis',
        'Penetration Tester' => 'Penetration testing',
        'Security Consultant' => 'Security consulting',
        'Security Auditor' => 'security Auditor work',
        'Compliance Officer' => 'Compliance services',
        'Hardware Engineer' => 'Hardware engineering work',
        'Embedded Systems Engineer' => 'Embedded Systems engineering work',
        'Firmware Engineer' => 'Firmware engineering work',
        'PCB Designer' => 'PCB design work',
        'IoT Developer' => 'IoT development work',
        'Other IT / hardware work' => 'other IT / hardware work',
    ],

    'Design, Media & Creative' => [
        'Graphic Designer' => 'Graphic design work',
        'Visual / Brand Designer' => 'Visual / Brand design work',
        'Logo Designer' => 'Logo design work',
        'Branding Kits' => 'branding kit work',
        'Packaging Designer' => 'Packaging design work',
        'UI/UX Designer' => 'UI/UX design work',
        'UX Researcher' => 'UX research',
        'Motion Graphics Designer' => 'Motion Graphics design work',
        '2D/3D Animator' => '2D/3D animation work',
        'Video Editor' => 'Video editing',
        'Photography' => 'photography work',
        'Real Estate Photography' => 'real estate photography',
        'Photo Editing' => 'photo editing',
        'Animation' => 'animation work',
        'Game Artist' => 'Game art work',
        'Presentation Designer' => 'Presentation design work',
        'CAD Designer' => 'CAD design work',
        '3D Modelling' => '3D modelling',
        'Printing / Signage design' => 'printing and signage design',
        'Other design / creative work' => 'other design / creative work',
    ],

    'Product, Project, Business & Marketing' => [
        'Product Manager' => 'Product management',
        'Project Manager' => 'Project management',
        'Scrum Master' => 'Scrum facilitation',
        'Business Analyst' => 'Business analysis',
        'Systems Analyst' => 'Systems analysis',
        'CRM Specialist' => 'CRM services',
        'Salesforce Developer' => 'Salesforce development work',
        'Salesforce Administrator' => 'Salesforce administration',
        'ERP Consultant' => 'ERP consulting',
        'QA Tester' => 'QA testing',
        'QA Automation Engineer' => 'QA Automation engineering work',
        'Technical Writer' => 'Technical writing',
        'Content Writer' => 'Content writing',
        'Copywriter' => 'copywriter work',
        'Digital Marketer' => 'Digital marketing',
        'SEO Specialist' => 'SEO services',
        'PPC Specialist' => 'PPC services',
        'Social Media Manager' => 'Social Media management',
        'Community Manager' => 'Community management',
        'Email Marketer' => 'Email marketing',
        'Growth Hacker' => 'Growth work',
        'E-learning Developer' => 'E-learning development work',
        'Instructional Designer' => 'Instructional design work',
        'IT Trainer' => 'IT training',
        'Localization Specialist' => 'Localization services',
        'Performance Engineer' => 'Performance engineering work',
        'Operations Consultant' => 'Operations consulting',
        'Other product / marketing work' => 'other product / marketing work',
    ],

    'Building, Construction & Finishing' => [
        'Bricklaying / Masonry' => 'bricklaying / Masonry work',
        'Blockwork / Concreting' => 'blockwork / Concreting work',
        'Carpentry / Woodwork' => 'carpentry / Woodwork work',
        'Cabinet / Furniture making' => 'cabinet / Furniture making work',
        'Iron bending / Steel fixing' => 'iron bending / Steel fixing work',
        'Welding / Metal fabrication' => 'welding / Metal fabrication work',
        'Aluminium / Glass installation' => 'aluminium / Glass installation',
        'Roofing / Roof repair' => 'roofing / Roof repair',
        'Plastering / POP ceiling' => 'plastering / POP ceiling work',
        'Tiling / Floor work' => 'tiling / Floor work',
        'Interlocking / Paving stones' => 'interlocking / Paving stones work',
        'Painting / Decorating' => 'painting / Decorating work',
        'Interior decorating' => 'interior decorating work',
        'Scaffolding' => 'scaffolding work',
        'Site labour / General building' => 'site labour / General building work',
        'Quantity surveying support' => 'quantity surveying support',
        'Other building / construction work' => 'other building / construction work',
    ],

    'Electrical, Power & Solar' => [
        'House wiring / Electrical install' => 'house wiring / Electrical install',
        'Electrical repair / Fault finding' => 'electrical repair / Fault finding',
        'Distribution board / Meter work' => 'distribution board / Meter work',
        'Generator install / service' => 'generator install / service',
        'Generator repair' => 'generator repair',
        'Inverter / Battery install' => 'inverter / Battery install',
        'Solar panel install' => 'solar panel install',
        'Solar / inverter repair' => 'solar / inverter repair',
        'Streetlight / outdoor lighting' => 'streetlight / outdoor lighting work',
        'Industrial electrical work' => 'industrial electrical work',
        'Other electrical / power work' => 'other electrical / power work',
    ],

    'Plumbing, Water & Gas' => [
        'Plumbing install' => 'plumbing install',
        'Plumbing repair / Leak fix' => 'plumbing repair',
        'Borehole drilling / servicing' => 'borehole drilling / servicing work',
        'Water pump install / repair' => 'water pump install / repair',
        'Water treatment / filtration' => 'water treatment / filtration work',
        'Septic / soakaway work' => 'septic / soakaway work',
        'Gas piping / cooker install' => 'gas piping / cooker install',
        'Gas cooker repair' => 'gas cooker repair',
        'Other plumbing / water work' => 'other plumbing / water work',
    ],

    'AC, Refrigeration & Appliances' => [
        'AC installation' => 'aC installation',
        'AC repair / gas refill' => 'aC repair / gas refill',
        'AC servicing / cleaning' => 'aC servicing / cleaning',
        'Fridge / freezer repair' => 'fridge / freezer repair',
        'Washing machine repair' => 'washing machine repair',
        'Cooker / oven repair' => 'cooker / oven repair',
        'Microwave / small appliance repair' => 'microwave / small appliance repair',
        'Other AC / appliance work' => 'other AC / appliance work',
    ],

    'Auto, Transport & Mobility' => [
        'Auto mechanic (engine / general)' => 'auto mechanic (engine / general) work',
        'Auto electrician' => 'auto electrician work',
        'Panel beating / body work' => 'panel beating / body work',
        'Auto painting / spraying' => 'auto painting / spraying work',
        'Wheel alignment / balancing' => 'wheel alignment / balancing work',
        'Vulcanizing / tyre repair' => 'vulcanizing / tyre repair',
        'Motorcycle / Okada mechanic' => 'motorcycle / Okada mechanic work',
        'Tricycle (Keke) mechanic' => 'tricycle (Keke) mechanic work',
        'Car AC repair' => 'car AC repair',
        'Car detailing / washing' => 'car detailing / washing work',
        'Towing / recovery' => 'towing / recovery work',
        'Private / commercial driving' => 'private / commercial driving work',
        'Courier / delivery run' => 'courier / delivery run',
        'Other auto / transport work' => 'other auto / transport work',
    ],

    'Phones, Gadgets & Electronics' => [
        'Phone screen / hardware repair' => 'phone screen / hardware repair',
        'Phone software / unlock' => 'phone software / unlock work',
        'Laptop / PC repair' => 'laptop / PC repair',
        'Laptop / PC upgrade' => 'laptop / PC upgrade work',
        'CCTV / security camera install' => 'cCTV / security camera install',
        'Satellite / DSTV install' => 'satellite / DSTV install',
        'POS / card machine setup' => 'pOS / card machine setup',
        'Printer / office equipment repair' => 'printer / office equipment repair',
        'Home theatre / AV install' => 'home theatre / AV install',
        'Other gadget / electronics work' => 'other gadget / electronics work',
    ],

    'Beauty, Fashion & Personal Care' => [
        'Hairdressing / styling' => 'hairdressing / styling work',
        'Barbering' => 'barbering work',
        'Makeup artistry' => 'makeup artistry work',
        'Nail technician / manicure' => 'nail technician / manicure work',
        'Spa / massage therapy' => 'spa / massage therapy work',
        'Fashion design / sewing' => 'fashion design / sewing work',
        'Tailoring / alterations' => 'tailoring / alterations work',
        'Beadwork / accessories' => 'beadwork / accessories work',
        'Shoe making / cobbling' => 'shoe making / cobbling work',
        'Dry cleaning / laundry' => 'dry cleaning / laundry',
        'Other beauty / fashion work' => 'other beauty / fashion work',
    ],

    'Events, Catering & Hospitality' => [
        'Event planning / coordination' => 'event planning / coordination',
        'Event decoration / canopy' => 'event decoration / canopy work',
        'Catering / event cooking' => 'catering / event cooking work',
        'DJ / MC services' => 'dJ / MC services',
        'Live band / entertainment' => 'live band / entertainment',
        'Photography (events)' => 'photography (events)',
        'Videography (events)' => 'videography (events) work',
        'Ushering / protocol' => 'ushering / protocol',
        'Venue setup / teardown' => 'venue setup / teardown',
        'Cake / pastry for events' => 'cake / pastry for events work',
        'Other events / hospitality work' => 'other events / hospitality work',
    ],

    'Cleaning, Facility & Estate Services' => [
        'Domestic / home cleaning' => 'domestic / home cleaning',
        'Office / commercial cleaning' => 'office / commercial cleaning',
        'Deep / post-construction cleaning' => 'deep / post-construction cleaning',
        'Carpet / sofa cleaning' => 'carpet / sofa cleaning',
        'Fumigation / pest control' => 'fumigation / pest control work',
        'Waste disposal / evacuation' => 'waste disposal / evacuation work',
        'Gardening / landscaping' => 'gardening / landscaping work',
        'Facility management' => 'facility management',
        'Estate / compound maintenance' => 'estate / compound maintenance',
        'Other cleaning / facility work' => 'other cleaning / facility work',
    ],

    'Health, Wellness & Care' => [
        'Home nursing / caregiver' => 'home nursing / caregiver work',
        'Physiotherapy support' => 'physiotherapy support',
        'First aid / emergency response' => 'first aid / emergency response work',
        'Pharmacy delivery / support' => 'pharmacy delivery / support',
        'Fitness training / coaching' => 'fitness training / coaching',
        'Nutrition / wellness consulting' => 'nutrition / wellness consulting work',
        'Childcare / nanny' => 'childcare / nanny work',
        'Elderly care' => 'elderly care',
        'Other health / care work' => 'other health / care work',
    ],

    'Education, Tutoring & Training' => [
        'Subject tutoring (primary / secondary)' => 'subject tutoring (primary / secondary)',
        'WAEC / JAMB / exam prep' => 'wAEC / JAMB / exam prep work',
        'University / professional tutoring' => 'university / professional tutoring',
        'Language tutoring' => 'language tutoring',
        'Music lessons' => 'music lessons',
        'Driving school instruction' => 'driving school instruction work',
        'Vocational / skills training' => 'vocational / skills training',
        'Corporate training' => 'corporate training',
        'Other education / training work' => 'other education / training work',
    ],

    'Agriculture, Food & Agro-processing' => [
        'Farm labour / cultivation' => 'farm labour / cultivation',
        'Poultry / livestock care' => 'poultry / livestock care',
        'Fish farming support' => 'fish farming support',
        'Agrochemical / input application' => 'agrochemical / input application work',
        'Harvesting / processing' => 'harvesting / processing',
        'Food processing / packaging' => 'food processing / packaging',
        'Cold storage / logistics' => 'cold storage / logistics',
        'Veterinary support' => 'veterinary support',
        'Other agriculture / food work' => 'other agriculture / food work',
    ],

    'Logistics, Moving & Errands' => [
        'House / office moving' => 'house / office moving',
        'Packing / unpacking' => 'packing / unpacking',
        'Furniture assembly' => 'furniture assembly',
        'Interstate logistics' => 'interstate logistics',
        'Last-mile delivery' => 'last-mile delivery',
        'Shopping / errand running' => 'shopping / errand running',
        'Document / courier runs' => 'document / courier runs work',
        'Other logistics / errand work' => 'other logistics / errand work',
    ],

    'Professional, Legal & Admin Services' => [
        'Bookkeeping / accounting support' => 'bookkeeping / accounting support',
        'Tax filing assistance' => 'tax filing assistance',
        'Business registration support' => 'business registration support',
        'Virtual assistance' => 'virtual assistance',
        'Secretarial / admin support' => 'secretarial / admin support',
        'Notary / affidavit support' => 'notary / affidavit support',
        'Legal drafting support' => 'legal drafting support',
        'HR / recruitment support' => 'hR / recruitment support',
        'Insurance support' => 'insurance support',
        'Real estate agency support' => 'real estate agency support',
        'Other professional / admin work' => 'other professional / admin work',
    ],

    'Other' => [
        'General / unclassified job' => 'recent work',
        'Other' => 'other work',
    ],

];
