<?php

/**
 * Suggested skill tags for artisan public profiles.
 * Kept short and client-facing (what they hire for).
 */
return [
    // Electrical
    'Wiring & installations',
    'House wiring',
    'Rewiring',
    'DB / fuse box work',
    'Socket & switch fitting',
    'Lighting installation',
    'Generator service',
    'Inverter installation',
    'Solar & inverter',
    'Solar panel install',
    'CCTV & security cameras',
    'Security systems',
    'Smart home / IoT',
    'Networking',
    'Intercom systems',
    'Emergency call-outs',

    // Plumbing & AC
    'Plumbing fixtures',
    'Pipe repairs',
    'Water heater install',
    'Borehole & pump work',
    'Toilet / soakaway',
    'AC & refrigeration',
    'AC installation',
    'AC gas refill',
    'Fridge repairs',

    // Building & finishing
    'New builds',
    'Renovations',
    'Tiling & finishing',
    'Painting & coating',
    'Pop & ceiling work',
    'Plastering',
    'Bricklaying',
    'Aluminium & glass',
    'Doors & windows',
    'Roofing',
    'Waterproofing',
    'Interior work',
    'Exterior work',
    'Finishing & detail work',

    // Fabrication & metal
    'Welding',
    'Custom fabrication',
    'Metal gates & burglary',
    'Iron bending',
    'Furniture making',
    'Carpentry',
    'Cabinet making',
    'Upholstery',

    // Auto
    'Auto diagnostics',
    'Engine repairs',
    'Panel beating',
    'Spray painting',
    'Auto electrical',
    'Wheel alignment',
    'Car AC service',

    // Beauty, events, food
    'Bridal / glam',
    'Makeup',
    'Hair styling',
    'Nail tech',
    'Tailoring & fashion',
    'Event setup',
    'Decoration',
    'Catering',
    'Small chops & drinks',
    'DJ & sound',
    'Photo & video',
    'Videography',

    // Digital & business
    'Web & apps',
    'Branding & design',
    'Graphic design',
    'SEO & marketing',
    'Social media management',
    'Phone repairs',
    'Computer repairs',

    // General service styles
    'Repairs & maintenance',
    'Preventive maintenance',
    'Troubleshooting',
    'Site surveys',
    'Quotations & estimates',
    'Material sourcing',
    'Same-day service',
    'Commercial projects',
    'Residential projects',

    // Nigerian market additions
    'Screeding',
    'Kitchen cabinets',
    'Wardrobes & closets',
    'Gypsum / false ceiling',
    'Marble & granite',
    'Epoxy flooring',
    'Interlocking stones',
    'Texture finishes',
    'Changeover / ATS',
    'Stabilizer / UPS',
    'Electric fence',
    'Industrial electrical',
    'Overhead tank work',
    'Water treatment',
    'Drainage clearing',
    'Gas piping',
    'Gas cooker service',
    'AC servicing',
    'Washing machine repair',
    'Cooker / oven repair',
    'Small appliance repair',
    'Brake & suspension',
    'Battery service',
    'Tyre & vulcanizing',
    'Okada / keke repairs',
    'Car audio & alarms',
    'Window tinting',
    'Car detailing',
    'Towing & recovery',
    'Private driving',
    'Courier runs',
    'Satellite / DSTV',
    'POS setup',
    'POS agent support',
    'Biometric devices',
    'Printer repair',
    'Home theatre / AV',
    'Barbering',
    'Beard grooming',
    'Wig install',
    'Gele tying',
    'Traditional bridal',
    'Lash & brow',
    'Ankara / aso-ebi',
    'Traditional wear',
    'Beadwork',
    'Leatherworks',
    'Shoe repair',
    'Laundry & dry cleaning',
    'Canopy & backdrop',
    'Suya & grill',
    'Cakes & pastry',
    'Bartending',
    'PA systems',
    'Ushering',
    'MC services',
    'Home cleaning',
    'Office cleaning',
    'Post-construction clean',
    'Carpet & sofa clean',
    'Floor polishing',
    'Fumigation',
    'Septic evacuation',
    'Waste disposal',
    'Gardening',
    'Tree felling',
    'Facility management',
    'Estate maintenance',
    'Home nursing',
    'Elderly care',
    'Childcare',
    'Fitness coaching',
    'Nutrition advice',
    'First aid support',
    'Subject tutoring',
    'Exam prep (WAEC / JAMB)',
    'Language tutoring',
    'Music lessons',
    'Driving instruction',
    'Vocational training',
    'Corporate training',
    'Farm labour',
    'Poultry care',
    'Fish farming',
    'Agrochemicals',
    'Harvest processing',
    'Food packaging',
    'Cold storage',
    'House moving',
    'Packing',
    'Furniture assembly',
    'Interstate logistics',
    'Last-mile delivery',
    'Water tanker',
    'Diesel delivery',
    'Cooking gas delivery',
    'Errand running',
    'Private guarding',
    'Access control',
    'Fire safety',
    'Locksmith',
    'Security consultancy',
    'Flex & banners',
    'Vehicle branding',
    'Shop signage',
    'Large-format print',
    'Souvenirs',
    'Screen printing',
    'Stationery print',
    'Canopy hire',
    'Chair & table hire',
    'Generator hire',
    'Sound / PA hire',
    'Cooler hire',
    'Lighting hire',
    'Scaffolding hire',
    'Event equipment',
    'Curtains & blinds',
    'Mattress & foam',
    'Wallpaper',
    'Carpet install',
    'Soft furnishings',
    'WordPress',
    'E-commerce',
    'API integrations',
    'Mobile apps',
    'Cross-platform apps',
    'Game development',
    'Data analysis',
    'Dashboards',
    'Research & reports',
    'AI automation',
    'IT support',
    'Cloud setup',
    'Cybersecurity',
    'Server setup',
    'Hardware repair',
    'UI/UX',
    'Motion graphics',
    'Printing & signage',
    'Project management',
    'Content writing',
    'CRM setup',
    'Bookkeeping',
    'Tax filing',
    'Business registration',
    'Virtual assistance',
    'Admin support',
    'HR support',
    'Real estate support',
];
