<?php

/**
 * Suggested skills grouped by job category parent.
 * Used at signup so artisans see skills relevant to their craft.
 * Flat list in config/skills.php remains the full searchable catalog.
 */
return [
    'Building, Construction & Finishing' => [
        'New builds',
        'Renovations',
        'Bricklaying',
        'Blockwork & concreting',
        'Screeding',
        'Carpentry',
        'Cabinet making',
        'Kitchen cabinets',
        'Wardrobes & closets',
        'Welding',
        'Custom fabrication',
        'Metal gates & burglary',
        'Aluminium & glass',
        'Doors & windows',
        'Roofing',
        'Waterproofing',
        'Pop & ceiling work',
        'Gypsum / false ceiling',
        'Tiling & finishing',
        'Marble & granite',
        'Epoxy flooring',
        'Interlocking stones',
        'Painting & coating',
        'Texture finishes',
        'Interior work',
        'Exterior work',
        'Scaffolding',
        'Site surveys',
        'Quotations & estimates',
        'Material sourcing',
        'Residential projects',
        'Commercial projects',
    ],

    'Electrical, Power & Solar' => [
        'Wiring & installations',
        'House wiring',
        'Rewiring',
        'DB / fuse box work',
        'Socket & switch fitting',
        'Lighting installation',
        'Changeover / ATS',
        'Stabilizer / UPS',
        'Generator service',
        'Inverter installation',
        'Solar & inverter',
        'Solar panel install',
        'Electric fence',
        'Industrial electrical',
        'Emergency call-outs',
        'Troubleshooting',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
    ],

    'Plumbing, Water & Gas' => [
        'Plumbing fixtures',
        'Pipe repairs',
        'Water heater install',
        'Borehole & pump work',
        'Overhead tank work',
        'Water treatment',
        'Toilet / soakaway',
        'Drainage clearing',
        'Gas piping',
        'Gas cooker service',
        'Emergency call-outs',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
    ],

    'AC, Refrigeration & Appliances' => [
        'AC & refrigeration',
        'AC installation',
        'AC gas refill',
        'AC servicing',
        'Fridge repairs',
        'Washing machine repair',
        'Cooker / oven repair',
        'Small appliance repair',
        'Emergency call-outs',
        'Same-day service',
        'Preventive maintenance',
    ],

    'Auto, Transport & Mobility' => [
        'Auto diagnostics',
        'Engine repairs',
        'Panel beating',
        'Spray painting',
        'Auto electrical',
        'Wheel alignment',
        'Brake & suspension',
        'Car AC service',
        'Battery service',
        'Tyre & vulcanizing',
        'Okada / keke repairs',
        'Car audio & alarms',
        'Window tinting',
        'Car detailing',
        'Towing & recovery',
        'Private driving',
        'Courier runs',
    ],

    'Phones, Gadgets & Electronics' => [
        'Phone repairs',
        'Computer repairs',
        'CCTV & security cameras',
        'Security systems',
        'Satellite / DSTV',
        'POS setup',
        'POS agent support',
        'Biometric devices',
        'Printer repair',
        'Home theatre / AV',
        'Networking',
        'Intercom systems',
        'Smart home / IoT',
    ],

    'Beauty, Fashion & Personal Care' => [
        'Hair styling',
        'Barbering',
        'Beard grooming',
        'Wig install',
        'Gele tying',
        'Makeup',
        'Bridal / glam',
        'Traditional bridal',
        'Lash & brow',
        'Nail tech',
        'Spa & massage',
        'Tailoring & fashion',
        'Ankara / aso-ebi',
        'Traditional wear',
        'Beadwork',
        'Leatherworks',
        'Shoe repair',
        'Laundry & dry cleaning',
    ],

    'Events, Catering & Hospitality' => [
        'Event setup',
        'Decoration',
        'Canopy & backdrop',
        'Catering',
        'Small chops & drinks',
        'Suya & grill',
        'Cakes & pastry',
        'Bartending',
        'DJ & sound',
        'PA systems',
        'Photo & video',
        'Videography',
        'Ushering',
        'MC services',
    ],

    'Cleaning, Facility & Estate Services' => [
        'Home cleaning',
        'Office cleaning',
        'Post-construction clean',
        'Carpet & sofa clean',
        'Floor polishing',
        'Fumigation',
        'Septic evacuation',
        'Drainage clearing',
        'Waste disposal',
        'Gardening',
        'Tree felling',
        'Facility management',
        'Estate maintenance',
    ],

    'Health, Wellness & Care' => [
        'Home nursing',
        'Elderly care',
        'Childcare',
        'Fitness coaching',
        'Nutrition advice',
        'First aid support',
    ],

    'Education, Tutoring & Training' => [
        'Subject tutoring',
        'Exam prep (WAEC / JAMB)',
        'Language tutoring',
        'Music lessons',
        'Driving instruction',
        'Vocational training',
        'Corporate training',
    ],

    'Agriculture, Food & Agro-processing' => [
        'Farm labour',
        'Poultry care',
        'Fish farming',
        'Agrochemicals',
        'Harvest processing',
        'Food packaging',
        'Cold storage',
    ],

    'Logistics, Moving & Errands' => [
        'House moving',
        'Packing',
        'Furniture assembly',
        'Interstate logistics',
        'Last-mile delivery',
        'Water tanker',
        'Diesel delivery',
        'Cooking gas delivery',
        'Errand running',
        'Courier runs',
    ],

    'Security, Access Control & Safety' => [
        'Private guarding',
        'Access control',
        'Intercom systems',
        'Electric fence',
        'Fire safety',
        'Locksmith',
        'CCTV & security cameras',
        'Security systems',
        'Security consultancy',
    ],

    'Printing, Signage & Outdoor Media' => [
        'Flex & banners',
        'Vehicle branding',
        'Shop signage',
        'Large-format print',
        'Souvenirs',
        'Screen printing',
        'Stationery print',
        'Graphic design',
        'Branding & design',
    ],

    'Equipment Hire & Rentals' => [
        'Canopy hire',
        'Chair & table hire',
        'Generator hire',
        'Sound / PA hire',
        'Cooler hire',
        'Lighting hire',
        'Scaffolding hire',
        'Event equipment',
    ],

    'Soft Furnishings & Fit-out' => [
        'Curtains & blinds',
        'Upholstery',
        'Mattress & foam',
        'Wallpaper',
        'Carpet install',
        'Soft furnishings',
        'Interior work',
    ],

    'Software, Web & E-commerce Development' => [
        'Web & apps',
        'WordPress',
        'E-commerce',
        'API integrations',
        'Branding & design',
        'SEO & marketing',
    ],

    'Mobile, Game & AR/VR Development' => [
        'Web & apps',
        'Mobile apps',
        'Cross-platform apps',
        'Game development',
    ],

    'Data, AI & Analytics' => [
        'Data analysis',
        'Dashboards',
        'Research & reports',
        'AI automation',
    ],

    'DevOps, Cloud, IT, Cybersecurity & Hardware' => [
        'IT support',
        'Networking',
        'Cloud setup',
        'Cybersecurity',
        'Server setup',
        'Hardware repair',
    ],

    'Design, Media & Creative' => [
        'Graphic design',
        'Branding & design',
        'UI/UX',
        'Photo & video',
        'Videography',
        'Motion graphics',
        'Printing & signage',
    ],

    'Product, Project, Business & Marketing' => [
        'Project management',
        'Digital marketing',
        'SEO & marketing',
        'Social media management',
        'Content writing',
        'CRM setup',
    ],

    'Professional, Legal & Admin Services' => [
        'Bookkeeping',
        'Tax filing',
        'Business registration',
        'Virtual assistance',
        'Admin support',
        'HR support',
        'Real estate support',
    ],

    'Other' => [
        'Repairs & maintenance',
        'Troubleshooting',
        'Site surveys',
        'Quotations & estimates',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
    ],
];
