<?php

/**
 * Suggested skills grouped by job category parent.
 * Used at signup so artisans only see skills relevant to their craft.
 * Tuned for Nigerian client language and hiring patterns.
 *
 * Each group must list at least 20 skills.
 */
return [
    'Building, Construction & Finishing' => [
        'New builds',
        'House extensions',
        'Renovations',
        'Bricklaying',
        'Blockwork & concreting',
        'Foundation casting',
        'Screeding',
        'Plastering',
        'Rendering',
        'Carpentry',
        'Roof carpentry',
        'Cabinet making',
        'Kitchen cabinets',
        'Wardrobes & closets',
        'Furniture making',
        'Welding',
        'Custom fabrication',
        'Metal gates & burglary',
        'Iron bending',
        'Aluminium & glass',
        'Doors & windows',
        'Roofing',
        'Longspan roofing',
        'Waterproofing',
        'Pop & ceiling work',
        'Gypsum / false ceiling',
        'Tiling & finishing',
        'Marble & granite',
        'Epoxy flooring',
        'Interlocking stones',
        'Painting & coating',
        'Texture finishes',
        'Interior work',
        'Exterior work',
        'Scaffolding',
        'Site surveys',
        'Quotations & estimates',
        'Material sourcing',
        'Residential projects',
        'Commercial projects',
        'Estate / compound work',
        'Demolition & clearing',
    ],

    'Electrical, Power & Solar' => [
        'House wiring',
        'Rewiring',
        'DB / fuse box work',
        'Socket & switch fitting',
        'Lighting installation',
        'Chandelier & pendant fitting',
        'Changeover / ATS',
        'Stabilizer / UPS',
        'Generator installation',
        'Generator service',
        'Inverter installation',
        'Solar & inverter',
        'Solar panel install',
        'Battery bank setup',
        'Electric fence',
        'CCTV power cabling',
        'Industrial electrical',
        '3-phase connections',
        'Meter / prepaid board work',
        'NEPA / Disco connection support',
        'Earthing & bonding',
        'Surge protection',
        'Troubleshooting',
        'Emergency call-outs',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
        'Quotations & estimates',
        'Preventive maintenance',
        'Wiring & installations',
    ],

    'Plumbing, Water & Gas' => [
        'Plumbing fixtures',
        'Pipe repairs',
        'PVC & PPR piping',
        'Water heater install',
        'Instant heater fitting',
        'Borehole drilling support',
        'Borehole & pump work',
        'Submersible pump install',
        'Overhead tank work',
        'Underground tank work',
        'Water treatment',
        'Water filter install',
        'Toilet / soakaway',
        'Septic tank work',
        'Drainage clearing',
        'Rainwater harvesting',
        'Gas piping',
        'Gas cooker service',
        'Kitchen sink install',
        'Bathroom fittings',
        'Shower cubicle install',
        'Leak detection',
        'Emergency call-outs',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
        'Quotations & estimates',
        'Preventive maintenance',
        'Material sourcing',
        'Repairs & maintenance',
    ],

    'AC, Refrigeration & Appliances' => [
        'AC installation',
        'AC servicing',
        'AC gas refill',
        'AC relocation',
        'Split unit repair',
        'Window unit repair',
        'Central / VRF systems',
        'Fridge repairs',
        'Deep freezer repair',
        'Washing machine repair',
        'Dryer repair',
        'Cooker / oven repair',
        'Microwave repair',
        'Water dispenser repair',
        'Small appliance repair',
        'Cold room setup',
        'Ice machine service',
        'Compressor replacement',
        'Thermostat & PCB repair',
        'Preventive maintenance',
        'Emergency call-outs',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
        'Quotations & estimates',
        'AC & refrigeration',
        'Troubleshooting',
        'Repairs & maintenance',
        'Material sourcing',
        'Site surveys',
    ],

    'Auto, Transport & Mobility' => [
        'Auto diagnostics',
        'Engine repairs',
        'Gearbox / transmission',
        'Clutch work',
        'Panel beating',
        'Spray painting',
        'Auto electrical',
        'Wheel alignment',
        'Brake & suspension',
        'Car AC service',
        'Battery service',
        'Alternator / starter',
        'Tyre & vulcanizing',
        'Okada / keke repairs',
        'Car audio & alarms',
        'Window tinting',
        'Car detailing',
        'Interior cleaning',
        'Towing & recovery',
        'Private driving',
        'Courier runs',
        'CNG / LPG conversion support',
        'Key programming',
        'Scanner / OBD diagnostics',
        'Oil & filter service',
        'Radiator & cooling',
        'Fuel pump & injector work',
        'Body filler & refinish',
        'Fleet maintenance',
        'Quotations & estimates',
    ],

    'Phones, Gadgets & Electronics' => [
        'Phone screen replacement',
        'Phone charging port repair',
        'Phone water damage',
        'Phone unlocking / flashing',
        'Laptop repairs',
        'Computer repairs',
        'Laptop screen / keyboard',
        'Data recovery',
        'CCTV & security cameras',
        'Security systems',
        'Satellite / DSTV',
        'Decoder install',
        'POS setup',
        'POS agent support',
        'Biometric devices',
        'Printer repair',
        'Home theatre / AV',
        'TV repair',
        'Networking',
        'Router / Wi‑Fi setup',
        'Intercom systems',
        'Smart home / IoT',
        'Power bank & gadget repair',
        'Game console repair',
        'Software install & setup',
        'Same-day service',
        'Emergency call-outs',
        'Quotations & estimates',
        'Troubleshooting',
        'Repairs & maintenance',
    ],

    'Beauty, Fashion & Personal Care' => [
        'Hair styling',
        'Barbering',
        'Beard grooming',
        'Hair colouring',
        'Braiding & cornrows',
        'Wig install',
        'Wig making',
        'Gele tying',
        'Makeup',
        'Bridal / glam',
        'Traditional bridal',
        'Lash & brow',
        'Nail tech',
        'Pedicure & manicure',
        'Spa & massage',
        'Facials & skincare',
        'Tailoring & fashion',
        'Ankara / aso-ebi',
        'Traditional wear',
        'Agbada & native wear',
        'Beadwork',
        'Leatherworks',
        'Shoe repair',
        'Bag making',
        'Laundry & dry cleaning',
        'Alterations & fittings',
        'Home service / mobile glam',
        'Children’s haircare',
        'Henna / tattoos (henna)',
        'Quotations & estimates',
    ],

    'Events, Catering & Hospitality' => [
        'Event setup',
        'Decoration',
        'Canopy & backdrop',
        'Chair arrangement',
        'Catering',
        'Small chops & drinks',
        'Suya & grill',
        'Cakes & pastry',
        'Owambe / party catering',
        'Corporate catering',
        'Bartending',
        'DJ & sound',
        'PA systems',
        'Photo & video',
        'Videography',
        'Live streaming',
        'Ushering',
        'MC services',
        'Protocol & guest management',
        'Event planning',
        'Wedding planning',
        'Traditional wedding support',
        'Lighting for events',
        'Cooler & ice supply',
        'Waiter service',
        'Venue styling',
        'Same-day service',
        'Quotations & estimates',
        'Material sourcing',
        'Residential projects',
    ],

    'Cleaning, Facility & Estate Services' => [
        'Home cleaning',
        'Office cleaning',
        'Deep cleaning',
        'Post-construction clean',
        'Carpet & sofa clean',
        'Mattress cleaning',
        'Floor polishing',
        'Window cleaning',
        'Fumigation',
        'Pest control',
        'Septic evacuation',
        'Drainage clearing',
        'Waste disposal',
        'Gardening',
        'Lawn care',
        'Tree felling',
        'Facility management',
        'Estate maintenance',
        'Generator compound cleaning',
        'Tank cleaning',
        'Swimming pool cleaning',
        'Janitorial contracts',
        'Move-in / move-out clean',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
        'Quotations & estimates',
        'Preventive maintenance',
        'Repairs & maintenance',
        'Material sourcing',
    ],

    'Health, Wellness & Care' => [
        'Home nursing',
        'Elderly care',
        'Childcare',
        'Nanny services',
        'Postnatal care',
        'Physiotherapy support',
        'Fitness coaching',
        'Personal training',
        'Yoga / stretch coaching',
        'Nutrition advice',
        'Meal planning',
        'First aid support',
        'Wound care support',
        'Medication reminders',
        'Hospital companion',
        'Disability care support',
        'Mental wellness coaching',
        'Weight management coaching',
        'Sports conditioning',
        'Live-in care',
        'Day-care support',
        'Health check coordination',
        'Same-day service',
        'Residential projects',
        'Quotations & estimates',
        'Preventive maintenance',
        'Emergency call-outs',
        'Corporate wellness',
        'Home service visits',
        'Client education',
    ],

    'Education, Tutoring & Training' => [
        'Subject tutoring',
        'Exam prep (WAEC / JAMB)',
        'UTME / post-UTME prep',
        'IGCSE / SAT / IELTS prep',
        'Primary school tutoring',
        'Secondary school tutoring',
        'Language tutoring',
        'English fluency coaching',
        'Yoruba / Igbo / Hausa tutoring',
        'Music lessons',
        'Piano / keyboard lessons',
        'Guitar lessons',
        'Driving instruction',
        'Vocational training',
        'Trade skills training',
        'Corporate training',
        'Soft skills training',
        'Computer literacy training',
        'Coding for beginners',
        'Homework support',
        'Homeschool support',
        'Adult literacy',
        'Exam coaching (professional)',
        'Presentation skills coaching',
        'Public speaking coaching',
        'Online tutoring',
        'Home service tutoring',
        'Group classes',
        'Curriculum planning',
        'Quotations & estimates',
    ],

    'Agriculture, Food & Agro-processing' => [
        'Farm labour',
        'Land clearing',
        'Crop farming',
        'Poultry care',
        'Broiler management',
        'Layer management',
        'Fish farming',
        'Catfish / pond management',
        'Snail farming',
        'Livestock care',
        'Agrochemicals',
        'Fertilizer application',
        'Irrigation setup',
        'Greenhouse farming',
        'Harvest processing',
        'Food packaging',
        'Cold storage',
        'Cassava processing',
        'Palm oil processing',
        'Garri / flour processing',
        'Feed formulation',
        'Farm advisory',
        'Soil testing support',
        'Nursery & seedlings',
        'Bee keeping',
        'Market linkage support',
        'Quotations & estimates',
        'Material sourcing',
        'Preventive maintenance',
        'Same-day service',
    ],

    'Logistics, Moving & Errands' => [
        'House moving',
        'Office relocation',
        'Packing',
        'Furniture assembly',
        'Furniture disassembly',
        'Interstate logistics',
        'Last-mile delivery',
        'Same-day delivery',
        'Water tanker',
        'Diesel delivery',
        'Cooking gas delivery',
        'Errand running',
        'Courier runs',
        'Document dispatch',
        'Airport pickup / drop',
        'School run support',
        'Market shopping runs',
        'Heavy item lifting',
        'Warehouse handling',
        'Bike dispatch',
        'Van / truck hire coordination',
        'Fragile item handling',
        'Loading & offloading',
        'Storage support',
        'Quotations & estimates',
        'Commercial projects',
        'Residential projects',
        'Emergency call-outs',
        'Material sourcing',
        'Same-day service',
    ],

    'Security, Access Control & Safety' => [
        'Private guarding',
        'Estate security',
        'Access control',
        'Intercom systems',
        'Electric fence',
        'Fire safety',
        'Fire extinguisher service',
        'Locksmith',
        'Key cutting',
        'Safe opening & install',
        'CCTV & security cameras',
        'Security systems',
        'Alarm systems',
        'Biometric access',
        'Security consultancy',
        'Risk assessment',
        'Night watch coordination',
        'Crowd control support',
        'VIP protection support',
        'Gate automation',
        'Panic button install',
        'Security lighting',
        'Patrol scheduling',
        'Incident reporting',
        'Emergency call-outs',
        'Same-day service',
        'Residential projects',
        'Commercial projects',
        'Quotations & estimates',
        'Preventive maintenance',
    ],

    'Printing, Signage & Outdoor Media' => [
        'Flex & banners',
        'Roll-up banners',
        'Vehicle branding',
        'Shop signage',
        '3D signage',
        'Large-format print',
        'Souvenirs',
        'Screen printing',
        'Stationery print',
        'Business cards & flyers',
        'Wedding invitation print',
        'Graphic design',
        'Branding & design',
        'Logo design',
        'Billboard artwork',
        'Sticker & label print',
        'Mug / souvenir branding',
        'ID card printing',
        'UV / outdoor printing',
        'Plotting & cutting',
        'Installation of signage',
        'Light box fabrication',
        'Exhibition stand branding',
        'Packaging design print',
        'Same-day service',
        'Quotations & estimates',
        'Material sourcing',
        'Commercial projects',
        'Residential projects',
        'Site surveys',
    ],

    'Equipment Hire & Rentals' => [
        'Canopy hire',
        'Chair & table hire',
        'Generator hire',
        'Sound / PA hire',
        'Cooler hire',
        'Lighting hire',
        'Scaffolding hire',
        'Event equipment',
        'Projector & screen hire',
        'Stage hire',
        'Fan / AC hire',
        'Cooker & cooler hire',
        'Tent / gazebo hire',
        'Plastic chair hire',
        'VIP sofa hire',
        'Carpet / aisle runner hire',
        'Photo booth hire',
        'Camera equipment hire',
        'Ladder & tool hire',
        'Concrete mixer hire',
        'Delivery of hired items',
        'Setup & teardown',
        'Same-day service',
        'Quotations & estimates',
        'Weekend / owambe packages',
        'Corporate event packages',
        'Residential projects',
        'Commercial projects',
        'Material sourcing',
        'Emergency call-outs',
    ],

    'Soft Furnishings & Fit-out' => [
        'Curtains & blinds',
        'Roman blinds',
        'Sheer curtains',
        'Upholstery',
        'Sofa reupholstery',
        'Mattress & foam',
        'Custom bed frames',
        'Wallpaper',
        'Carpet install',
        'Rug fitting',
        'Soft furnishings',
        'Interior work',
        'Cushion & throw making',
        'Headboard upholstery',
        'Office seating reupholstery',
        'Leather sofa repair',
        'Foam replacement',
        'Window treatments',
        'Mosquito net fitting',
        'Pelmet & cornice work',
        'Space planning advice',
        'Colour consultation',
        'Site surveys',
        'Quotations & estimates',
        'Material sourcing',
        'Residential projects',
        'Commercial projects',
        'Same-day service',
        'Repairs & maintenance',
        'Finishing & detail work',
    ],

    'Software, Web & E-commerce Development' => [
        'Web & apps',
        'WordPress',
        'Shopify stores',
        'E-commerce',
        'API integrations',
        'Branding & design',
        'SEO & marketing',
        'Frontend development',
        'Backend development',
        'Full-stack development',
        'Laravel / PHP',
        'React / Vue',
        'Node.js',
        'Python / Django',
        'Database design',
        'Payment integrations',
        'Paystack / Flutterwave setup',
        'Hosting & deployment',
        'Website redesign',
        'Landing pages',
        'Admin dashboards',
        'Multi-vendor marketplaces',
        'WhatsApp / SMS integrations',
        'Business website setup',
        'Performance optimisation',
        'Security hardening',
        'Maintenance retainers',
        'Quotations & estimates',
        'Client training',
        'Bug fixes & support',
    ],

    'Mobile, Game & AR/VR Development' => [
        'Mobile apps',
        'Android development',
        'iOS development',
        'Flutter',
        'React Native',
        'Cross-platform apps',
        'Game development',
        '2D games',
        '3D games',
        'Unity',
        'AR / VR',
        'App store publishing',
        'Play Store publishing',
        'API integrations',
        'UI/UX',
        'Push notifications',
        'In-app payments',
        'Paystack / Flutterwave mobile',
        'Offline-first apps',
        'WhatsApp-style chat features',
        'Location / maps features',
        'App maintenance',
        'Bug fixes & support',
        'Prototype / MVP builds',
        'Game assets support',
        'Performance optimisation',
        'Quotations & estimates',
        'Client training',
        'Web & apps',
        'Branding & design',
    ],

    'Data, AI & Analytics' => [
        'Data analysis',
        'Dashboards',
        'Research & reports',
        'AI automation',
        'Machine learning',
        'Excel / spreadsheets',
        'Google Sheets automation',
        'Power BI / Tableau',
        'Python for data',
        'SQL',
        'Business intelligence',
        'Data cleaning',
        'Data entry',
        'Data labelling',
        'Predictive models',
        'Survey design',
        'Market research',
        'Sales analytics',
        'Customer analytics',
        'KPI tracking',
        'Report automation',
        'ChatGPT / AI workflows',
        'Prompt engineering',
        'ETL / data pipelines',
        'Database querying',
        'Quotations & estimates',
        'Client training',
        'Dashboard Creation',
        'Presentation of insights',
        'Ongoing analytics retainers',
    ],

    'DevOps, Cloud, IT, Cybersecurity & Hardware' => [
        'IT support',
        'Helpdesk support',
        'Networking',
        'Office LAN / Wi‑Fi setup',
        'Cloud setup',
        'AWS / Azure / GCP',
        'Cybersecurity',
        'Server setup',
        'Hardware repair',
        'CI/CD pipelines',
        'Docker / containers',
        'Linux administration',
        'Windows server admin',
        'Backup & recovery',
        'Firewall & VPN',
        'Endpoint security',
        'Email / Microsoft 365 setup',
        'Google Workspace setup',
        'Domain & DNS setup',
        'CCTV network setup',
        'POS / terminal networking',
        'Printer & peripheral setup',
        'Asset inventory',
        'Vulnerability assessment',
        'Security awareness training',
        'Preventive maintenance',
        'Emergency call-outs',
        'Quotations & estimates',
        'Commercial projects',
        'Same-day service',
    ],

    'Design, Media & Creative' => [
        'Graphic design',
        'Branding & design',
        'Logo design',
        'UI/UX',
        'Photo & video',
        'Videography',
        'Motion graphics',
        'Printing & signage',
        'Social media creatives',
        'Flyer & poster design',
        'Product photography',
        'Event photography',
        'Wedding photography',
        'Drone photography',
        'Video editing',
        'YouTube content editing',
        'Reels / TikTok edits',
        'Illustration',
        'Packaging design',
        'Presentation design',
        'Thumbnail design',
        'Colour grading',
        'Voice-over support',
        'Studio setup advice',
        'Content calendars',
        'Quotations & estimates',
        'Commercial projects',
        'Residential projects',
        'Same-day service',
        'Client training',
    ],

    'Product, Project, Business & Marketing' => [
        'Project management',
        'Digital marketing',
        'SEO & marketing',
        'Social media management',
        'Content writing',
        'Copywriting',
        'CRM setup',
        'Product management',
        'Business planning',
        'Go-to-market strategy',
        'Facebook / Instagram ads',
        'Google ads',
        'WhatsApp marketing',
        'Email marketing',
        'Influencer coordination',
        'Brand strategy',
        'Sales funnel setup',
        'Customer support playbooks',
        'Market research',
        'Competitor analysis',
        'Pitch deck creation',
        'Startup advisory',
        'Process documentation',
        'Agile / scrum facilitation',
        'KPI dashboards',
        'Quotations & estimates',
        'Client training',
        'Retainer management',
        'Campaign reporting',
        'Lead generation systems',
    ],

    'Professional, Legal & Admin Services' => [
        'Bookkeeping',
        'Tax filing',
        'VAT / WHT support',
        'Business registration',
        'CAC registration support',
        'Virtual assistance',
        'Admin support',
        'HR support',
        'Payroll support',
        'Real estate support',
        'Property management admin',
        'Contract drafting support',
        'Notary coordination',
        'Company secretarial support',
        'Immigration / visa paperwork',
        'Document preparation',
        'Meeting scheduling',
        'Customer service ops',
        'Inventory admin',
        'Procurement support',
        'Office management',
        'Reception / front desk',
        'Data entry',
        'Transcription',
        'Quotations & estimates',
        'Client training',
        'Compliance checklists',
        'Audit preparation support',
        'Bank account opening support',
        'Same-day service',
    ],

    'Other' => [
        'Repairs & maintenance',
        'Troubleshooting',
        'Site surveys',
        'Quotations & estimates',
        'Material sourcing',
        'Same-day service',
        'Emergency call-outs',
        'Residential projects',
        'Commercial projects',
        'Preventive maintenance',
        'Custom fabrication',
        'Installation & fitting',
        'Consultation visits',
        'After-sales support',
        'Training & handover',
        'Project coordination',
        'Quality inspection',
        'Waste & debris clearing',
        'Tool & equipment advice',
        'Multi-trade coordination',
        'Weekend / rush jobs',
        'Estate / compound work',
        'Mobile / on-site service',
        'Warranty follow-up',
        'Client education',
        'Safety compliance',
        'Finishing & detail work',
        'Demolition & clearing',
        'Packaging & delivery support',
        'General handyman work',
    ],
];
