<?php

/**
 * Common Nigerian artisan / service trades for registration.
 * Keep "Other" last so free-text entry stays available.
 */
return [
    'AC / Refrigeration technician',
    'Aluminium / Glass installer',
    'Auto electrician',
    'Auto mechanic',
    'Auto painter / Sprayer',
    'Battery charger / Inverter tech',
    'Borehole / Water technician',
    'Bricklayer / Mason',
    'Cabinet / Furniture maker',
    'Carpenter',
    'Caterer / Event cook',
    'CCTV / Security installer',
    'Cleaner / Janitorial',
    'Cobbler / Shoe maker',
    'Disk jockey (DJ)',
    'Driver (private / commercial)',
    'Dry cleaner / Laundry',
    'Electrician',
    'Event decorator / Canopy',
    'Fashion designer / Tailor',
    'Gas cooker technician',
    'Generator technician',
    'Graphic designer / Printer',
    'Hairdresser / Barber',
    'Iron bender / Steel fixer',
    'Interior decorator',
    'Interlocking / Paving stone',
    'Makeup artist',
    'Motorcycle / Okada mechanic',
    'Nail technician',
    'Painter / Decorator',
    'Panel beater',
    'Phone / Laptop repair',
    'Photographer / Videographer',
    'Plasterer / POP ceiling',
    'Plumber',
    'POS / Signage installer',
    'Roofer',
    'Satellite / TV installer',
    'Solar installer',
    'Tiler',
    'Tricycle (Keke) mechanic',
    'Upholsterer',
    'Vulcanizer / Tyre repair',
    'Welder / Fabricator',
    'Other',
];
